FROM python:3.7-alpine

ARG TAG=latest

# CONFIGURACION
WORKDIR /usr/src/
COPY ./src/ .


# DEPENDENCIAS
RUN pip install -r requirements.txt --upgrade pip


# VARIABLES PREDEFINIDAS
ENV VERSION=${TAG}

ENV PYTHON_HOST=0.0.0.0
ENV PYTHON_PORT=5000
ENV PYTHON_GUNICORN_WORKERS=2
ENV PYTHON_GUNICORN_CONNECTIONS=500
ENV PYTHON_NOMBRE_APP=app
ENV PYTHON_NOMBRE_FUNCION_APP=app


# EJECUCION
EXPOSE ${PYTHON_PORT}

CMD gunicorn \
    -b ${PYTHON_HOST}:${PYTHON_PORT} \
    --reload \
    --workers=${PYTHON_GUNICORN_WORKERS} \
    --worker-connections=${PYTHON_GUNICORN_CONNECTIONS} \
    ${PYTHON_NOMBRE_APP}:${PYTHON_NOMBRE_FUNCION_APP}