version: 2.1

##################################################################
# WORFLOWS
##################################################################
workflows:
  despliegue_de_master:
    jobs:
      - creacion_de_docker:
          filters:
            branches:
              only: master

##################################################################
# EXECUTORS
##################################################################
executors:
  ejecutor-base:
    machine:
      enabled: true
    working_directory: ~/proyect

##################################################################
# JOBS
##################################################################
jobs:
  creacion_de_docker:
    executor: ejecutor-base
    steps:
      - attach_workspace:
          at: ~/proyect
      - checkout
      - run:
          name: build
          command: ./scripts/docker/build.sh
      - run:
          name: push
          command: ./scripts/docker/push.sh
